### ISSUE TITLE
last time i open this project ,it doesnot work

### ISSUE THREAD

**Issue by stickylabdev** [andersonaddo/Dimension-Dash#1]
why

**Comment by andersonaddo** [comment]
First of all, you should really make it a habit to make more informative issues (I can see from your issue history that you often make one worded issue posts - not too helpful). There is a bunch of useful info that you should have included, like your Unity version, the errors your were getting, your OS and even when this "last time" was.

I'm going to assume that you're using the latest version of Unity. As stated in the README, this project does work on Unity 2018.1.3f1. However, since around Unity 2018.3, Unity made [breaking changes ](https://blogs.unity3d.com/2018/06/20/introducing-new-prefab-workflows/)to their prefab system. So, running pre-2018.3 projects with newer versions will cause a bunch of errors.

Run the game on Unity 2018.1.3f1 and it should be fine.

Also, if you were trying to run the project so that you could make a build APK, I've actaully made an APK available in this repo's [releases](https://github.com/andersonaddo/Dimension-Dash/releases) section.

**Comment by stickylabdev** [comment]
aah ok , mine is 2018..3.9f1 ,,

Pada tanggal Sel, 10 Des 2019 pukul 23.30 Anderson Addo <
notifications@github.com> menulis:
